### ISSUE TITLE
JMH silently fails with unknown typed literals

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.core#106]
I tried to add an extended property and by mistake supplied a UriBuilder instead of a URI object. JMH skipped the property without a warning.

**Comment by berezovskyi** [comment]
Nope, I was wrong:

```
scott_twins.1@linuxkit-025000000001    | java.lang.IllegalArgumentException: don't know how to parse a org.glassfish.jersey.uri.internal.JerseyUriBuilder
scott_twins.1@linuxkit-025000000001    | 	at org.apache.jena.graph.impl.AdhocDatatype.parse(AdhocDatatype.java:39)
scott_twins.1@linuxkit-025000000001    | 	at org.apache.jena.graph.impl.LiteralLabelImpl.setValue(LiteralLabelImpl.java:217)
```
