### ISSUE TITLE
UriBuilder calls seem to depend on JAX-RS 2.0 API

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.core#31]
During the startup of an adaptor, the following exception is thrown:

```
java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;
	at javax.ws.rs.core.UriBuilder.fromUri(UriBuilder.java:119)
	at org.eclipse.lyo.oslc4j.core.OSLC4JUtils.servletUriBuilderFrom(OSLC4JUtils.java:478)
```

I initially suspected the problem with some leftover JAX-RS 1.1 maven dependencies, which has lead me to attempt removing `jsr311-api` from the trs-server repo: https://github.com/eclipse/lyo.trs-server/pull/7. Only later I understood that Wink never supported JAX-RS 2.0 and instead it is likely that we accidentally depend on some JAX-RS 2.0 APIs before having migrated to Jersey!

I will keep this issue updated as my investigation progresses.

**Comment by berezovskyi** [comment]
The issue only manifests itself on Jetty 9.4. Going back to Jetty 9.3 as a workaround.

**Comment by berezovskyi** [comment]
Wontfix, Lyo is JAX-RS 2.0 compliant now
